### ISSUE TITLE
Clicking the editable nodes causes pipes to stack up.

### ISSUE THREAD

**Issue by SpyR1014** [SpyR1014/vue-graphViz#10]
#### Issue description

If you click on editable nodes multiple times, the observables don't cancel and many cursors are added.

#### Steps to reproduce the issue

1. Create an editable node.
2.  Spam click on the editable node

#### What's the expected result?

Multiple pipes shouldn't appear. 

#### What's the actual result?

The node will have many pipes: '|' of previous cursors.

**Comment by theya222** [comment]
nodes now use a html editor instead of simulation vs svg, bug no longer applicable
