### ISSUE TITLE
add new node to graph 

### ISSUE THREAD

**Issue by monalena** [SpyR1014/vue-graphViz#5]
could you add an icon to the toolbar so we can also create new nodes?

**Comment by SpyR1014** [comment]
Is this for nodes that can be edited?
I'll try to add editable nodes by Wednesday.

I'm also giving you collaborator access so that you can make changes freely.

**Comment by monalena** [comment]
Look, sorry, maybe I’m not getting it.
At the moment, the tool I open through the vue component:

- is unable to create new nodes
- automatically loads the text chunk nodes on the left side and not via a button (in case I don’t want to work with the text chunks and create new nodes instead)
- I cannot change their shape or color 
- or content text
- I cannot pin single nodes down or switch of the web cola entirely

Will all of this be able through the methods you are adding to your graph object and then once I figure out how to add font awesome icons I can connect them to your methods?

Thanks for giving me collaborator access,
Monika

**Comment by SpyR1014** [comment]
Currently this component only fulfils the **Structure Map** part of the design spec.

From the design spec it currently supports:
**Interaction with Text Interface**
Points 2, 3 and 4.

Most of the points you've raised are the concept map points. I haven't implemented them into this component yet. Need to hear from Ivo if I need to transpile this, or if ES6 is fine. Also need to hear if it's ok to include [RxJS](https://github.com/Reactive-Extensions/RxJS) library.

Currently I have focussed on getting the Structure Map working. So the node styles should be based on the node type provided.

There is no pin tool yet.

**Comment by monalena** [comment]
Thanks for clarifying, Andrew. I didn’t realise you were working through this systematically.

Richard asked me today where we are with the concept mapping tool and if we can plan it in for the beta, I said yes.
I think for the beta release the concept part has to work as well. (My hunch is that people will use it rather as a concept than a structure map.)

I’ll ask Ivo about ES6 and RxJS library in tomorrow’s meeting and get back to you on that. Or let him answer to you directly. 

Cheers,
Monika

**Comment by SpyR1014** [comment]
Also once I know Ivo's github username I'll add him as a contributor as well.

The [concept mapping demo](http://mind-map-prototype.surge.sh/) that has the node adding and text editing of nodes is this repo:
https://github.com/SpyR1014/mind-map-prototype

It's not very readable. But it's the implementations of the text editing and node adding. Once I'm more sure about the vue implementations I'll port the features over.
